blog/urls.py
from django.conf.urls import url

from . import views

app_name = "blog"

urlpatterns = [
    url(r'^index/$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page, name='article_page'),
    url(r'^create/$', views.create_page, name='create_page'),
    url(r'^edit/(?P<article_id>[0-9]+)$', views.edit_page, name='edit_page'),
    url(r'^create/action$', views.create_action, name='create_action'),
    url(r'^edit/action$', views.edit_action, name='edit_action'),
    url(r'^delete/(?P<article_id>[0-9]+)$', views.delete_action, name='article_delete'),

]

testdj/urls.py
from django.contrib import admin
from django.conf.urls import url, include

#import  blog.views as  bv


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)

    # 3.6 使用str #2.7 使用unicode
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from . import models
from django.shortcuts import redirect

# 博客主页
def index(request):
    #根据主键获取对象
    #article = models.Article.objects.get(pk=1)
    articles = models.Article.objects.all()
    #return render(request, 'blog/index.html', {'hello': 'hello,Blog!1234'});
    return render(request, 'blog/index.html', {'articles': articles});


# 博客详情页面
def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article});


# 进入新增页面
def create_page(request):
    return render(request, 'blog/create_page.html');


# 进入编辑页面
def edit_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article});


def create_action(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    models.Article.objects.create(title=title, content=content)
    return redirect('/blog/index/')


def edit_action(request):
    article_id = request.POST.get('id', 'ID')
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    models.Article.objects.filter(id=article_id).update(title=title, content=content)
    return redirect('/blog/index/')


def delete_action(request, article_id):
    models.Article.objects.filter(id=article_id).delete()
    return redirect('/blog/index/')

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<h3>{{ article.content }}</h3>
<br>
<br>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

blog/templates/blog/create_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form  action="{% url 'blog:create_action' %}" method="post">
    {% csrf_token %}
    <label>title:</label>
    <input type="text" name="title"/>
    <br>
    <label>content:</label>
     <input type="text" name="content"/>
    <br>
    <input type="submit">
</form>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form  action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    <label>title:</label>
     <input type="hidden" name="id" value="{{ article.id }}"/>
    <input type="text" name="title" value="{{ article.title }}"/>
    <br>
    <label>content:</label>
     <input type="text" name="content" value="{{ article.content }}"/>
    <br>
    <input type="submit">
</form>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1><a href="{% url 'blog:create_page' %}">新文章</a></h1>

    {% for article in articles %}
        <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
        <a href="{% url 'blog:article_delete' article.id %}">删除</a>
        <br>
    {% endfor %}
</body>
</html>